[project]
name = "cookiecutter"
version = "0.1.0"
description = "Add a short description here"
authors = ["Moritz Wilksch <moritzwilksch@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"

[pypi-dependencies]
my_pkg = { path = ".", editable = true }

[feature.lint.dependencies]
mypy = "*"
ruff = "*"
taplo = "*"

[feature.lint.tasks]
lint = "ruff check --fix . && taplo format && mypy ."

[feature.dev.dependencies]
ipykernel = "*"

[feature.build.dependencies]
hatchling = "*"

[environments]
default = ["lint", "dev", "build"]
dev = ["dev"]
lint = ["lint"]
