[project]
name = "cookiecutter"
version = "0.1.0"
description = "Add a short description here"
authors = ["Moritz Wilksch <moritzwilksch@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"

[pypi-dependencies]
my_pkg = { path = ".", editable = true }

[feature.lint.dependencies]
ruff = "*"
pre-commit = "*"
mypy = "*"

[feature.dev.dependencies]
ipykernel = "*"

[environments]
default = ["lint", "dev"]
dev = ["dev"]
lint = ["lint"]
