[project]
name = "code"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pytorch = "2.3.*"
pytorch-cuda = "12.1.*"
ipykernel = ">=6.29.3,<6.30"

[system-requirements]
cuda = "12"